name: Build

on:
  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ./publish
        retention-days: 7
