name: Deploy

on:
  workflow_dispatch:

  push:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Descargar artefacto
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml  # Asegura que viene del workflow correcto
          workflow_conclusion: success  # Solo descarga si el build fue exitoso
          name: build-artifact
          path: C:\Temp\Deploy

      - name: Desplegar en D:\CICD
        run: |
          Remove-Item -Recurse -Force D:\CICD\* -ErrorAction SilentlyContinue
          Move-Item -Path C:\Temp\Deploy\* -Destination D:\CICD -Force
        shell: pwsh
