name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Descargar artefacto
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml  # Asegura que viene del workflow correcto
          workflow_conclusion: success  # Solo descarga si el build fue exitoso
          name: build-artifact
          path: C:\Temp\Deploy
          allow_forks: true

      - name: Desplegar en D:\CICD
        run: |
          Remove-Item -Recurse -Force D:\CICD\* -ErrorAction SilentlyContinue
          Start-Sleep -s 5  # Wait for a few seconds to ensure the delete operation completes
          Move-Item -Path C:\Temp\Deploy\* -Destination D:\CICD -Force
        shell: pwsh
